### ISSUE TITLE
[todo] Split Me v2

### ISSUE THREAD

**Issue by Manoz** [Manoz/split-me#5]
Build the v2 of this theme from scratch.

- Should require at least: WordPress 4.7
- Will see if I create a new repo for this

- [x] Build the theme skeleton  
- [x] Create the HomePage  
- [x] Site Header  
  - [x] Custom background for the header  
- [ ] Global Pages
- [x] Archives, Categories, Tags Pages
- [x] Search feature
- [x] Single Posts Skeletons
  - [x] Single post styles and content
  - [x] Posts formats
  - [x] Comments
- [ ] Footer
